stages:
  - build

image: node:16.16.0
      
build:
  stage: build
  script:
    - cd /builds/22_HF077/deploy-gongants_untact_study_room/client/
    - npm run deploy:install
    - cd /builds/22_HF077/deploy-gongants_untact_study_room/server/
    - npm i apidoc -g
    - npm run deploy:install
    - npm run dev
