stages:
  - build

image: node:latest
      
build:
  stage: build
  script:
    - cd /builds/22_HF077/gongants_untact_study_room-deploy/client/
    - npm run deploy:install
    - cd /builds/22_HF077/gongants_untact_study_room-deploy/server/
    - npm i apidoc -g
    - npm run deploy:install
    - npm run dev
                 
