stages:
  - build

before_script:
  - docker info

build:
  stage: build
  script:
    - cd /builds/22_HF077/deploy-gongants_untact_study_room/server/
    - docker build . -t gongants-docker/gongants-deploy:latest
    - docker run -p 4000:4000 -d gongants-docker/gongants-deploy:latest
