export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const USER_LOADING_REQUEST = 'USER_LOADING_REQUEST';
export const USER_LOADING_SUCCESS = 'USER_LOADING_SUCCESS';
export const USER_LOADING_FAILURE = 'USER_LOADING_FAILURE';

export const MEMO_WRITE_REQUEST = 'MEMO_REQUEST';
export const MEMO_WRITE_SUCCESS = 'MEMO_WRITE_SUCCESS';
export const MEMO_WRITE_FAILURE = 'MEMO_WRITE_FAILURE';

export const MEMO_LIST_REQUEST = 'MEMO_LIST_REQUEST';
export const MEMO_LIST_SUCCESS = 'MEMO_LIST_SUCCESS';
export const MEMO_LIST_FAILURE = 'MEMO_LIST_FAILURE';

export const MEMO_EDIT_REQUEST = 'MEMO_EDIT_REQUEST';
export const MEMO_EDIT_SUCCESS = 'MEMO_EDIT_SUCCESS';
export const MEMO_EDIT_FAILURE = 'MEMO_EDIT_FAILURE';

export const MEMO_UPDATE_REQUEST = 'MEMO_UPDATE_REQUEST';
export const MEMO_UPDATE_SUCCESS = 'MEMO_UPDATE_SUCCESS';
export const MEMO_UPDATE_FAILURE = 'MEMO_UPDATE_SUCCESS';

export const MEMO_DELETE_REQUEST = 'MEMO_DELETE_REQUEST';
export const MEMO_DELETE_SUCCESS = 'MEMO_DELETE_SUCCESS';
export const MEMO_DELETE_FAILURE = 'MEMO_DELETE_FAILURE';

export const SCHEDULE_LOADING_REQUEST = 'SCHEDULE_LOADING_REQUEST';
export const SCHEDULE_LOADING_SUCCESS = 'SCHEDULE_LOADING_SUCCESS';
export const SCHEDULE_LOADING_FAILURE = 'SCHEDULE_LOADING_FAILURE';

export const SCHEDULE_WRITE_REQUEST = 'SCHEDULE_WRITE_REQUEST';
export const SCHEDULE_WRITE_SUCCESS = 'SCHEDULE_WRITE_SUCCESS';
export const SCHEDULE_WRITE_FAILURE = 'SCHEDULE_WRITE_FAILURE';

export const SCHEDULE_DELETE_REQUEST = 'SCHEDULE_DELETE_REQUEST';
export const SCHEDULE_DELETE_SUCCESS = 'SCHEDULE_DELETE_SUCCESS';
export const SCHEDULE_DELETE_FAILURE = 'SCHEDULE_DELETE_FAILURE';

export const SCHEDULE_UPDATE_REQUEST = 'SCHEDULE_UPDATE_REQUEST';
export const SCHEDULE_UPDATE_SUCCESS = 'SCHEDULE_UPDATE_SUCCESS';
export const SCHEDULE_UPDATE_FAILURE = 'SCHEDULE_UPDATE_FAILURE';

export const SCHEDULE_EDIT_POPUP = 'SCHEDULE_EDIT_POPUP';

export const SCHEDULE_ISFILTER = 'SCHEDULE_ISFILTER';

export const SCHEDULE_FILTERTHISMONTH = 'SCHEDULE_FILTERTHISMONTH';

export const TODO_LOAD_REQUEST = 'TODO_LOAD_REQUEST';
export const TODO_LOAD_SUCCESS = 'TODO_LOAD_SUCCESS';
export const TODO_LOAD_FAILURE = 'TODO_LOAD_FAILURE';

export const TODO_TODAY_REQUEST = 'TODO_TODAY_REQUEST';
export const TODO_TODAY_SUCCESS = 'TODO_TODAY_SUCCESS';
export const TODO_TODAY_FAILURE = 'TODO_TODAY_FAILURE';

export const TODO_WRITE_REQUEST = 'TODO_WRITE_REQUEST';
export const TODO_WRITE_SUCCESS = 'TODO_WRITE_SUCCESS';
export const TODO_WRITE_FAILURE = 'TODO_WRITE_FAILURE';

export const TODO_DELETE_REQUEST = 'TODO_DELETE_REQUEST';
export const TODO_DELETE_SUCCESS = 'TODO_DELETE_SUCCESS';
export const TODO_DELETE_FAILURE = 'TODO_DELETE_FAILURE';
